export const ASSET_MAP = Object.freeze({
  heroPoster: "/assets/hero-poster.jpg",
  portrait: "/assets/legacy/image-001.jpg",
  wechatContent: "/assets/legacy/image-019.jpg",
  aiVideoPoster: "/assets/legacy/image-031.jpg",
  aiVideo: "/videos/projects/AI视频—BIOCARE.mp4",
  productDetail: "/assets/legacy/image-040.jpg",
  posterSeries: "/assets/legacy/image-003.jpg",
  workflow: "/assets/legacy/image-032.jpg",
  brandFilm: "/videos/projects/感物品牌地板.mp4",
  brandFilmPoster: "/assets/legacy/image-002.jpg",
  eventFilm: "/videos/projects/FENDI开业活动.mp4",
  eventFilmPoster: "/assets/legacy/image-027.jpg",
  biocareCampaign: "/assets/legacy/image-031.jpg",
  biocareProduct: "/assets/legacy/image-040.jpg",
  visualSystem: "/assets/legacy/image-041.jpg",
  wechatQr: "/assets/legacy/image-053.jpg",
  wanderer: "/assets/archive/wanderer.jpg",
  emptyRealm: "/assets/archive/empty-realm.jpg",
  yimusanfenVi: "/assets/archive/yimusanfen-vi.jpg",
  foodAppUi: "/assets/archive/food-app-ui.jpg",
  earlyPosterSeries: "/assets/archive/poster-series.jpg",
  packagingC4d: "/assets/archive/packaging-c4d.jpg",
});
